import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const templatePath = path.join(projectRoot, "docs/README.template.md");
const readmePath = path.join(projectRoot, "README.md");
const statusPath = path.join(projectRoot, "docs/STATUS.md");
const gates = fs.readFileSync(path.join(projectRoot, "GATES.md"), "utf8");
const parity = fs.readFileSync(path.join(projectRoot, "PARITY.md"), "utf8");

const gateRows = [...gates.matchAll(/^- \[([ xX])\] (G\d+): (.+)$/gm)].map((match) => ({
  id: match[2],
  title: match[3],
  met: match[1].toLowerCase() === "x",
}));
const met = gateRows.filter((gate) => gate.met);
const unmet = gateRows.filter((gate) => !gate.met);
const parityStatus = parity.match(/^Status:\s*(.+)$/m)?.[1] || "UNKNOWN";
const gateStatus = `Gate status: **${met.length}/${gateRows.length} met** (${unmet.length} remaining).`;
const parityLine = `Parity status: **${parityStatus}**. This is a generated project status, not a completion claim.`;

const template = fs.readFileSync(templatePath, "utf8");
const readme = template
  .replace("{{GATE_STATUS}}", gateStatus)
  .replace("{{PARITY_STATUS}}", parityLine);
fs.writeFileSync(readmePath, readme);

const statusLines = [
  "# Generated project status",
  "",
  "This file is regenerated by `scripts/update-docs.mjs` during every commit.",
  "",
  gateStatus,
  parityLine,
  "",
  "## Gates",
  "",
  ...gateRows.map((gate) => `- [${gate.met ? "x" : " "}] ${gate.id}: ${gate.title}`),
  "",
  `Reference: ${parity.match(/^- Reference shell: (.+)$/m)?.[1] || "unknown"}`,
];
fs.writeFileSync(statusPath, `${statusLines.join("\n")}\n`);

console.log(`OMARCHY_GPUI_DOCS_UPDATED: gates=${met.length}/${gateRows.length} parity=${parityStatus}`);
